[server]
port = ":8080"
worker_pool_size = 32
# idle_conns_per_host = 100

[cache]
enable = true
engine = "File" # File or Redis

  [cache.file]
    path = "/var/tmp/graid"

  [cache.redis]
    host = "localhost"
    port = ":6379"

  [cache.redis.pool]
    enable = true
    max_idle = 100

[origin]
url = "https://raw.githubusercontent.com/violetyk/graid/master/test_data"
