[server]
port = ":8080"
worker_pool_size = 32

[cache]
enable = false
engine = "Redis" # File or Redis

  [cache.file]
    path = "/var/tmp/graid"

  [cache.redis]
    host = "localhost"
    port = ":6379"

[origin]
url = "https://raw.githubusercontent.com/violetyk/graid/master/test_data"
